import type { Metadata } from "next";
import { DynaPuff, Outfit } from "next/font/google";

import "./globals.css";
import "@/custom-css/calendar.css";

import { ThemeProvider as MUIThemeProvider } from "@mui/material/styles";
import { NextUIProvider } from "@nextui-org/react";
import { muiTheme } from "@/themes";
import { Footer, Navbar } from "@/components";
import { Toaster } from "sonner";

const outfit = Outfit({
  weight: "variable",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-outfit",
});

const modak = DynaPuff({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-modak",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${modak.variable} ${outfit.className} antialiased`}>
        <MUIThemeProvider theme={muiTheme}>
          <NextUIProvider>
            {/* <AnimatedCursorProvider /> */}
            <Toaster />
            {/* <div className="absolute inset-0 z-0">
              <SparklesCore
                background="transparent"
                minSize={0.4}
                maxSize={1}
                particleDensity={50}
                particleColor="#10B981"
              />
            </div> */}
            <Navbar />
            {children}
            <Footer />
          </NextUIProvider>
        </MUIThemeProvider>
      </body>
    </html>
  );
}
